project:
  name: "shank-strut-bspline-mdo"
  author: "Jonathan Vollrath"

units:
  length: mm
  force: N
  stress: MPa
  mass: kg

geometry:
  symmetry:
    uses_symmetry: true
    symmetry_axis: "z-y plane"

  control_points:
    columns:
      - surface_id # possible values: shank_strut_surface
      - u_index # starts from 0
      - v_index # starts from 0
      - point_id # unique identifier for the control point
      - x
      - y
      - z
      - is_design_var # true or false depending on whether the point is editable
      - u_tag # optional tag for the point to help identify purpose
      - v_tag # optional tag for the point to help identify purpose

  holes:
    columns:
      - group_id # possible values: hole
      - hole_id # unique identifier for the hole
      - x
      - y
      - z
      - is_design_var # true or false depending on whether the point is editable
      - dim # diameter of the hole in mm
      - tag # optional tag for the hole to help identify purpose
    note: "The holes are defined as projections onto the surface, not strictly at their coordinates."

  surface_definition:
    type: "bicubic B-spline surface using Cox de-Boor recursion"
    u_degree: 3
    v_degree: 3
    knot_vector_u:
      [
        0,
        0,
        0,
        0,
        0.1111111111,
        0.2222222222,
        0.3333333333,
        0.4444444444,
        0.5555555556,
        0.6666666667,
        0.7777777778,
        0.8888888889,
        1,
        1,
        1,
        1,
      ]
    knot_vector_v: [0, 0, 0, 0, 1, 1, 1, 1]

analysis:
  u_samples: 100
  v_samples: 40
